# Generated by Django 5.2.6 on 2025-09-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.CharField(max_length=10),
        ),
    ]
