# Generated by Django 5.2.6 on 2025-09-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_transactions_category_alter_transactions_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='category',
            field=models.CharField(choices=[('salary', 'Salary'), ('food', 'Food'), ('rent', 'Rent'), ('travel', 'Travel'), ('entertainment', 'Entertainment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10),
        ),
    ]
