# Generated by Django 5.2.6 on 2025-09-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_transactions_category_alter_transactions_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='category',
            field=models.CharField(choices=[('Salary', 'Salary'), ('Food', 'Food'), ('Rent', 'Rent'), ('Travel', 'Travel'), ('Entertainment', 'Entertainment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=10),
        ),
    ]
